import { useCallback, useEffect, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, Movement, Product, Warehouse } from '@/lib/api';

const green='#23764f';
export default function MoveHistoryScreen(){const[rows,setRows]=useState<Movement[]>([]);const[products,setProducts]=useState<Product[]>([]);const[warehouses,setWarehouses]=useState<Warehouse[]>([]);const[product,setProduct]=useState('');const[warehouse,setWarehouse]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=useCallback(async()=>{setBusy(true);setError('');try{const[ledger,p,w]=await Promise.all([api<Movement[]>(`/dashboard/ledger?${product?`product=${product}&`:''}${warehouse?`warehouse=${warehouse}`:''}`),api<Product[]>('/products'),api<Warehouse[]>('/warehouses')]);setRows(ledger);setProducts(p);setWarehouses(w)}catch(e){setError(e instanceof Error?e.message:'Unable to load move history')}finally{setBusy(false)}},[product,warehouse]);
 // Async fetch on mount and when the ledger filters change.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor={green}/> }><Text style={styles.eyebrow}>AUDIT TRAIL</Text><Text style={styles.title}>Move history</Text><Text style={styles.sub}>Validated inventory changes</Text>{!!error&&<Text style={styles.error}>{error}</Text>}
 <Text style={styles.filterTitle}>PRODUCT</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}><Pill label="All" selected={!product} onPress={()=>setProduct('')}/>{products.map(p=><Pill key={p._id} label={p.name} selected={product===p._id} onPress={()=>setProduct(p._id)}/>)}</ScrollView>
 <Text style={styles.filterTitle}>WAREHOUSE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}><Pill label="All" selected={!warehouse} onPress={()=>setWarehouse('')}/>{warehouses.map(w=><Pill key={w._id} label={w.name} selected={warehouse===w._id} onPress={()=>setWarehouse(w._id)}/>)}</ScrollView>
 <Text style={styles.count}>{rows.length} ledger entries</Text>
 {rows.map(row=><View key={row._id} style={styles.card}><View style={styles.cardHead}><View style={styles.glyph}><Text style={styles.glyphText}>{row.operationType[0].toUpperCase()}</Text></View><View style={styles.main}><Text style={styles.name}>{row.product?.name||'Product'}</Text><Text style={styles.meta}>{row.product?.sku} · {new Date(row.createdAt).toLocaleString()}</Text></View><Text style={[styles.delta,row.quantityDelta<0?styles.negative:styles.positive]}>{row.quantityDelta>0?'+':''}{row.quantityDelta}</Text></View><Text style={styles.route}>{row.operationType} · {row.fromWarehouse?.name||'—'}  →  {row.toWarehouse?.name||'—'}</Text></View>)}
 {!rows.length&&!busy&&<View style={styles.empty}><Text style={styles.emptyTitle}>No movements yet</Text><Text style={styles.sub}>Validated receipts, deliveries, transfers and adjustments will appear here.</Text></View>}
 </ScrollView></SafeAreaView>}
function Pill({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.pill,selected&&styles.selected]}><Text numberOfLines={1} style={[styles.pillText,selected&&styles.selectedText]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f6'},content:{padding:20,paddingBottom:35,maxWidth:700,width:'100%',alignSelf:'center'},eyebrow:{color:'#96a199',fontSize:10,fontWeight:'800',letterSpacing:1.3,marginTop:6},title:{fontSize:27,fontWeight:'800',color:'#1d2a22',marginTop:4},sub:{color:'#8c9890',fontSize:12,marginTop:4},filterTitle:{fontSize:9,color:'#a0aaa3',fontWeight:'800',letterSpacing:1,marginTop:17,marginBottom:8},pills:{gap:7,paddingRight:8},pill:{maxWidth:190,paddingHorizontal:11,paddingVertical:8,borderRadius:30,borderWidth:1,borderColor:'#e2e8e3',backgroundColor:'#fff'},selected:{backgroundColor:'#e8f2eb',borderColor:'#d4e5d9'},pillText:{color:'#7b867f',fontSize:10,fontWeight:'600'},selectedText:{color:green,fontWeight:'800'},count:{fontSize:11,color:'#748078',fontWeight:'700',marginVertical:15},card:{backgroundColor:'#fff',borderRadius:13,padding:13,borderWidth:1,borderColor:'#edf0ed',marginBottom:9},cardHead:{flexDirection:'row',alignItems:'center',gap:9},glyph:{height:34,width:34,borderRadius:10,backgroundColor:'#edf4ef',alignItems:'center',justifyContent:'center'},glyphText:{color:green,fontSize:12,fontWeight:'800'},main:{flex:1},name:{color:'#36443b',fontSize:12,fontWeight:'800'},meta:{color:'#9ba59f',fontSize:9,marginTop:4},delta:{fontSize:12,fontWeight:'800'},positive:{color:'#31784e'},negative:{color:'#b45d51'},route:{color:'#8d9991',fontSize:10,textTransform:'capitalize',marginLeft:43,marginTop:8},empty:{alignItems:'center',backgroundColor:'#fff',borderRadius:14,padding:23,marginTop:5},emptyTitle:{color:'#39473f',fontSize:13,fontWeight:'800',marginBottom:5},error:{color:'#a94d42',backgroundColor:'#fff3f1',padding:10,borderRadius:8,fontSize:12,marginTop:12}});
