import { useCallback, useEffect, useState } from 'react';
import { Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, Product } from '@/lib/api';

const green = '#23764f';
export default function ProductsScreen() {
  const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [editing, setEditing] = useState<Product|null>(null); const [modalOpen, setModalOpen] = useState(false); const [form, setForm] = useState({ name:'', sku:'', category:'', unit:'pcs', reorderThreshold:'10' });
  const load = useCallback(async () => { setBusy(true); setError(''); try { setProducts(await api<Product[]>('/products')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load products'); } finally { setBusy(false); } }, []);
  // Async fetch on mount; state updates happen after the network response.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const filtered = products.filter(p => `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  const open = (product?: Product) => { setError(''); setEditing(product ?? null); setForm(product ? { name:product.name, sku:product.sku, category:product.category, unit:product.unit, reorderThreshold:String(product.reorderThreshold) } : { name:'', sku:'', category:'', unit:'pcs', reorderThreshold:'10' }); setModalOpen(true); };
  const save = async () => { setError(''); try { await api(editing ? `/products/${editing._id}` : '/products', { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ ...form, reorderThreshold:Number(form.reorderThreshold) }) }); setModalOpen(false); await load(); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to save product'); } };
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={() => void load()} tintColor={green}/> }>
    <View style={styles.head}><View><Text style={styles.eyebrow}>CATALOG</Text><Text style={styles.title}>Products</Text><Text style={styles.sub}>Inventory across your warehouses</Text></View><Pressable style={styles.add} onPress={() => open()}><Text style={styles.addText}>+ Add</Text></Pressable></View>
    <TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Search products or SKU" placeholderTextColor="#9ba69e"/>
    <View style={styles.summary}><View><Text style={styles.label}>Total products</Text><Text style={styles.count}>{products.length}</Text></View><View><Text style={styles.label}>Low / out</Text><Text style={[styles.count,{color:'#bd7e32'}]}>{products.filter(p=>p.stock.reduce((s,x)=>s+x.quantity,0)<=p.reorderThreshold).length}</Text></View></View>
    {!!error&&<Text style={styles.error}>{error}</Text>}
    {filtered.map(product => { const total=product.stock.reduce((s,x)=>s+x.quantity,0); return <Pressable key={product._id} onPress={()=>open(product)} style={styles.card}><View style={styles.cardTop}><View style={styles.productGlyph}><Text style={styles.glyphText}>{product.name.slice(0,1).toUpperCase()}</Text></View><View style={styles.productInfo}><Text style={styles.name}>{product.name}</Text><Text style={styles.meta}>{product.sku} · {product.category}</Text></View><Text style={[styles.stockFlag,total<=product.reorderThreshold?styles.low:styles.good]}>{total===0?'Out':total<=product.reorderThreshold?'Low':'Healthy'}</Text></View><View style={styles.divider}/><View style={styles.stockRow}><View><Text style={styles.label}>On hand</Text><Text style={styles.stock}>{total} {product.unit}</Text></View><View><Text style={styles.label}>Reorder at</Text><Text style={styles.stock}>{product.reorderThreshold} {product.unit}</Text></View></View><Text style={styles.warehouseLine}>{product.stock.map(s=>`${typeof s.warehouse==='object'?s.warehouse.name:'Warehouse'}: ${s.quantity}`).join('   ·   ')||'No stock movements yet'}</Text></Pressable>; })}
    {!filtered.length&&!busy&&<Text style={styles.empty}>{query?'No matching products.':'No products available.'}</Text>}
  </ScrollView><Modal visible={modalOpen} transparent animationType="slide" onRequestClose={()=>setModalOpen(false)}><View style={styles.modalShade}><View style={styles.modalCard}><View style={styles.modalHead}><Text style={styles.modalTitle}>{editing?'Edit product':'Add product'}</Text><Pressable onPress={()=>setModalOpen(false)}><Text style={styles.cancel}>Close</Text></Pressable></View>{!!error&&<Text style={styles.error}>{error}</Text>}{(['name','sku','category','unit','reorderThreshold'] as const).map(key=><View key={key} style={styles.formField}><Text style={styles.formLabel}>{key==='reorderThreshold'?'Reorder threshold':key[0].toUpperCase()+key.slice(1)}</Text><TextInput style={styles.formInput} value={form[key]} onChangeText={value=>setForm({...form,[key]:value})} keyboardType={key==='reorderThreshold'?'number-pad':'default'} autoCapitalize="none"/></View>)}<Pressable onPress={()=>void save()} style={styles.saveButton}><Text style={styles.saveText}>Save product</Text></Pressable></View></View></Modal></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f6'},content:{padding:20,paddingBottom:35,maxWidth:700,width:'100%',alignSelf:'center'},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:6,marginBottom:17},eyebrow:{color:'#96a199',fontSize:10,fontWeight:'800',letterSpacing:1.3},title:{fontSize:27,fontWeight:'800',color:'#1d2a22',marginTop:4},sub:{color:'#8c9890',fontSize:12,marginTop:4},add:{backgroundColor:green,borderRadius:10,paddingHorizontal:14,paddingVertical:10},addText:{color:'#fff',fontWeight:'700',fontSize:12},search:{height:44,borderRadius:11,borderWidth:1,borderColor:'#e6ebe7',backgroundColor:'#fff',paddingHorizontal:13,color:'#26332b',fontSize:13,marginBottom:13},summary:{flexDirection:'row',justifyContent:'space-between',backgroundColor:'#fff',padding:15,borderRadius:12,borderWidth:1,borderColor:'#edf0ed',marginBottom:12},label:{color:'#929d96',fontSize:10},count:{color:'#26332b',fontSize:22,fontWeight:'800',marginTop:4},card:{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:'#edf0ed',padding:14,marginBottom:10},cardTop:{flexDirection:'row',alignItems:'center',gap:10},productGlyph:{width:37,height:37,borderRadius:11,backgroundColor:'#edf4ef',alignItems:'center',justifyContent:'center'},glyphText:{color:green,fontWeight:'800',fontSize:15},productInfo:{flex:1},name:{color:'#2c3931',fontSize:13,fontWeight:'800'},meta:{color:'#99a39d',fontSize:10,marginTop:4},stockFlag:{fontSize:9,fontWeight:'800',paddingHorizontal:8,paddingVertical:5,borderRadius:20,overflow:'hidden'},low:{color:'#ad7939',backgroundColor:'#fff3e3'},good:{color:'#41805a',backgroundColor:'#eaf4ec'},divider:{height:1,backgroundColor:'#eef1ef',marginVertical:12},stockRow:{flexDirection:'row',gap:38},stock:{color:'#47544c',fontSize:12,fontWeight:'700',marginTop:4},warehouseLine:{color:'#99a39d',fontSize:10,marginTop:12},error:{color:'#a94d42',backgroundColor:'#fff3f1',padding:10,borderRadius:8,fontSize:12,marginBottom:10},empty:{textAlign:'center',padding:35,color:'#98a29c',fontSize:12},modalShade:{flex:1,justifyContent:'flex-end',backgroundColor:'#0006'},modalCard:{backgroundColor:'#fff',padding:22,paddingBottom:34,borderTopLeftRadius:22,borderTopRightRadius:22},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},modalTitle:{color:'#213028',fontSize:18,fontWeight:'800'},cancel:{color:green,fontSize:12,fontWeight:'700'},formField:{gap:5,marginBottom:10},formLabel:{color:'#6d7a71',fontSize:11,fontWeight:'700'},formInput:{height:43,borderRadius:9,borderWidth:1,borderColor:'#e2e8e3',paddingHorizontal:12,fontSize:14,color:'#26332b'},saveButton:{height:47,alignItems:'center',justifyContent:'center',backgroundColor:green,borderRadius:10,marginTop:6},saveText:{color:'#fff',fontSize:13,fontWeight:'800'}});
